---
- name: Base Amazon Linux install
  hosts: localhost
  become: true

  tasks:
    - name: Update all packages
      apt:
        name: "*"
        state: latest

    - name: Install packages
      apt:
        name:
          - htop
          - git-core
