---
- name: Base Amazon Linux install
  hosts: localhost
  become: true

  tasks:
  - name: Update all packages
    yum:
      name: "*"
      state: latest

  - name: Install packages
    yum:
      name:
        - htop
        - git-core

