---
- name: setup.yml playbook
  hosts: webservers
  gather_facts: no
  become: true
  user: ubuntu

  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python2-pip
      - wget
      - bind-utils
      - vim

  - name: Setting up a new user
    user:
      name: johnd
      comment: John Doe
  - name: Creating ssh-key for johnd
    user:
      name: johnd
      generate_ssh_key: yes
