---
- name: software.yml playbook
  hosts: all:!ec2-13-53-169-164.eu-north-1.compute.amazonaws.com
  gather_facts: no
  become: true
  user: ubuntu

  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - wget
      - vim
      - htop
      - screen

