---
- name: running all playbooks at once!
  hosts: all:!ec2-13-53-169-164.eu-north-1.compute.amazonaws.com
  user: ubuntu
  become: true

- name: importing newuser.yml
  import_playbook: newuser.yml

- name: importing software.yml
  import_playbook: software.yml
  
- name: importing mysqlserver.yml
  import_playbook: mysqlserver.yml

- name: importing webserver.yml
  import_playbook: webserver.yml
